version: '3'
services:
 mongodb:
   image: mongo:3.6
   expose:                 
     - "27017"
   volumes:
     - db_data:/data/db
   environment:    
    MONGODB_DATABASE: rsvpdata
   networks:
    - rsvpnet

 web:
   #image: teamcloudyuga/rsvpapp:mooc
   build: .
   ports:
    - "5000:5000"
   environment:
     LINK: http://www.meetup.com/iabai/
     TEXT1:
     TEXT2: IT Solutions
     LOGO: https://www.iab.ai/assets/iabai_logo_small.png
     COMPANY: IABAI SaS
     MONGODB_HOST: mongodb

   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
